version: '3.6'
services:
  pg_hasura:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hasura_db
    ports:
      - 5432:5432
    networks:
      - hasura_network
    volumes:
      - hasura_data:/var/lib/postgresql/data

  hasura:
    image: hasura/graphql-engine:v2.1.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - pg_hasura
    env_file:
      - .env
    networks:
      - hasura_network

  express_app:
    build:
      context: ./express-app
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - pg_hasura
      - hasura
    env_file:
      - .env
    networks:
      - hasura_network

volumes:
  hasura_data:

networks:
  hasura_network:
