version: '3.6'
services:
  keycloak:
    image: jboss/keycloak:16.1.1
    ports:
      - 8081:8080
      - 8443:8443
    depends_on:
      - pg_keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: pg_keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    networks:
      - hasura_network

  pg_keycloak:
    image: postgres:14.2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - pg_keycloak_data:/var/lib/postgresql/data
    networks:
      - hasura_network

volumes:
  pg_keycloak_data:

networks:
  hasura_network: